# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd browser-extension && npm ci --legacy-peer-deps
    - run: cd browser-extension && npm run build --if-present
    - name: Publish Chrome extension to Chrome Web Store
      uses: MobileFirstLLC/cws-publish@2.1.1
      with:
        # Desired action, one of: upload, publish, testers
        action: upload
        # Webstore API client id parameter
        client_id: ${{ secrets.CHROME_EXTENSION_CLIENT_ID }}
        # Webstore API client secret parameter
        client_secret: ${{ secrets.CHROME_EXTENSION_CLIENT_SECRET }}
        # Webstore API refresh token
        refresh_token: ${{ secrets.CHROME_EXTENSION_REFRESH_TOKEN }}
        # Path to extension .zip file
        zip_file: ./browser-extension/dist.zip 
        # Unique identifier of the Chrome extension
        extension_id: bfcjldhcnibiijidbbeddopkpljkahja
              
                
